### ISSUE TITLE
Bug: autoPVS1 unmet but still getting P/LP 

### ISSUE THREAD

**Issue by jungkim2** [diskin-lab-chop/AutoGVP#101]
#### Provide the command used or report the bug here

Variants that have no ClinVar call, and the reasoning for call is InterVar
InterVar calls it Pathogenic, and final output is Likely_pathogenic

InterVar: Pathogenic PVS1=1 PS=[0, 0, 0, 0, 0] PM=[0, 1, 0, 0, 0, 0, 0] PP=[0, 0, 1, 0, 0, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0, 0, 0, 0]

However, when autoPVS1 file is checked, it has NF4, unmet
Therefore, in this particular case, PVS1=1 should not be counted, therefore total counts would be PM=1, PP=1 VUS. 

7-93131357-C-A
7-93135631-G-T

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by rjcorb** [comment]
@jungkim2 I cannot locate these variants in any of the test files

**Comment by jungkim2** [comment]
they are not. These were found when I was testing different set of files that I wanted to test.

**Comment by naqvia** [comment]
Problem and issue resolved. AutoPVS1 related statements modified, tested and merged.
