### ISSUE TITLE
Feature request: code cleanup

### ISSUE THREAD

**Issue by jharenza** [diskin-lab-chop/AutoGVP#114]
#### Briefly descibe the feature and provide meaningful references
In the cases where we are joining two dataframes containing some of the same column names, we want to clean up the code to _not_ use `name.x` and `name.y` but rather name these based on the input dataframe. 

For example:
https://github.com/diskin-lab-chop/AutoGVP/blob/2ed5beb6873a599e1678f0f8cf7976cdafe4735e/AutoGVP/select-clinVar-submissions.R#L86-L91

#### Who will complete the feature request (please add a GitHub handle here if relevant)?

@naqvia

**Comment by naqvia** [comment]
no longer relevant
