### ISSUE TITLE
Bug:InterVar when there is both pathogenic and benign code

### ISSUE THREAD

**Issue by jungkim2** [diskin-lab-chop/AutoGVP#115]
#### Provide the command used or report the bug here

In cases of variants getting InterVar as a call,  when there is both pathogenic calls (PVS1, PS, PM, PP) and benign calls (BA1, BS, BP) it should be getting VUS call under Richards et al. table 5 with clause "the criteria for benign and pathogenic are contradictory”

some example variants

19-48703728-G-A
6-46716485-C-T

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by naqvia** [comment]
Fixed and merged.
