### ISSUE TITLE
Feature request: Add VEP command

### ISSUE THREAD

**Issue by naqvia** [diskin-lab-chop/AutoGVP#166]
#### Briefly descibe the feature and provide meaningful references
Please add/document the appropriate VEP command to have the proper refseq column output.

**Comment by jharenza** [comment]
@rjcorb or @rebkau can you inform here please?

**Comment by jharenza** [comment]
or @jungkim2 do you have further details on this?

**Comment by jungkim2** [comment]
I used below for my annotation

vep --offline --cache --dir_cache $VEP_CACHEDIR --fasta $VEP_CACHEDIR/GRCh38.fa --use_given_ref --species homo_sapiens --assembly GRCh38 --fork 1 --xref_refseq --hgvs --hgvsg --canonical --symbol --distance 0 --exclude_predicted --flag_pick --lookup_ref --force --input_file testing_010423.vcf --output_file testing_010423_VEP.vcf --format vcf --vcf --no_stats --numbers

I believe the key here is we musth have --xref_refseq

**Comment by jharenza** [comment]
closed with #197
