### ISSUE TITLE
adjusting/removing BP6 from InterVar codes

### ISSUE THREAD

**Issue by jungkim2** [diskin-lab-chop/AutoGVP#21]
Our reasoning behind removing PP5 is due to the below. This actually does apply to BP6 (benign code). Therefore, in addition to PP5 being disregarded in InterVar, BP6 also needs to be disregarded. 

"Finally, we are concerned that these two criteria may be commonly misused by laboratories that incorporate primary data into variant assessment (e.g., functional data, criteria PS3 and BS3) and at the same time invoke criteria PP5 and BP6 for existing classifications that are based on the same set of data, which may lead to double counting, and potentially lead to errors in classification." - directly from Biesecker et al.

**Comment by jharenza** [comment]
closed with #22
