### ISSUE TITLE
Update wiki to include recommendation of filtering DP>0

### ISSUE THREAD

**Issue by rjcorb** [diskin-lab-chop/AutoGVP#228]

**Comment by jharenza** [comment]
Related to https://gatk.broadinstitute.org/hc/en-us/articles/6012243429531-GenotypeGVCFs-and-the-death-of-the-dot

**Comment by rjcorb** [comment]
@jharenza I've updated the wiki at the filtering step, let me know what you think

**Comment by jharenza** [comment]
looks good, i just added GATK version number
