### ISSUE TITLE
Script missing

### ISSUE THREAD

**Issue by nandobonf** [diskin-lab-chop/AutoGVP#249]
Dear authors, 
I am trying to implement autoGVP in my pipeline, however, following the user guide at point 5:
`python autoPVS1_from_VEP_vcf.py --genome_version hg38 --vep_vcf test_VEP.vcf > test_autopvs1.txt`

It is not clear to me where the "autoPVS1_from_VEP_vcf.py" script is located. I do not see it available from the autoPVS1 page. 
Is it something you customized?
If yes, could you please share it?
Thanks in advance.

**Comment by jharenza** [comment]
Hi @nandobonf - thank you for bringing this to our attention. We indeed did customize AutoPVS1 to remove hg19 files, and lift over the gene symbols to be consistent with VEP 105 and to select specific transcripts based on rank. [Here](https://github.com/d3b-center/D3b-autoPVS1) is the version we had used in the manuscript, with the specific script of interest [here](https://github.com/d3b-center/D3b-autoPVS1/blob/main/autoPVS1_from_VEP_vcf.py).

We will try to update our documentation here to clarify, but please let us know if you have any further questions.

**Comment by jharenza** [comment]
The dockerfile for this version is:
```
docker pull pgc-images.sbgenomics.com/d3b-bixu/autopvs1:v2.0.0
```

**Comment by nandobonf** [comment]
Ok thanks for your feedback, that helps a lot. 
Wrt VEP, do I need to use the v104 as from the guidelines or the v105 as you write?

**Comment by jharenza** [comment]
Hi @nandobonf - I have updated the user guide to recommend using D3b AutoPVS1 to avoid confusion, and updated the link. Thank you for pointing it out. Will close this, but feel free to open an issue if you need anything else.
