### ISSUE TITLE
remove default gnomad filtering

### ISSUE THREAD

**Issue by jharenza** [diskin-lab-chop/AutoGVP#31]
Instead, replace with the user to input an optional column name - there is no guarantee that any of these will be named the same way across users, so we should make this a column input only

**Comment by naqvia** [comment]
Could you specific a bit more? I think we need to specific which version you're suggesting this to. Right now, the custom version has this capability with the `--gnomad_variable` option. However, the CAVATICA version does not bc we had initially decided it was `gnomad_3_1_1_AF_non_cancer` as this is reported in the input files from the pre-processing workflow. Are you suggesting that the output from the upstream workflow may change the gnomeAD variable/version?

**Comment by jharenza** [comment]
CAVATICA workflow fails because it is using `Freq_gnomad_genome_ALL` and also bc the preprocessed input files does not have the gnomad info we want to use for filtering - it will be in the new input VCF we need to accommodate per #32
