### ISSUE TITLE
final_call error on ClinVar 0 star

### ISSUE THREAD

**Issue by jungkim2** [diskin-lab-chop/AutoGVP#46]
There are variants that have 0 stars in ClinVar, intervar_adjusted_call:yes but still getting final_call as ClinVar classification

Below are some example variant vcf_id
1-149784224-C-T (https://www.ncbi.nlm.nih.gov/clinvar/variation/14826) Based on our criteria, it does get PVS1 and PP3 (InterVar also has PP5, but as we are dropping it, it should get VUS)

2-97250149-G-GC (https://www.ncbi.nlm.nih.gov/clinvar/variation/1320036) InterVar calls it LP (but with adjustment it should get VUS) but getting Benign call from ClinVar

**Comment by naqvia** [comment]
So I am just commenting on this so we don't lose track. These issues have been resolved, but related issue was detected. But I think its more to do with the original logic/clarity. This variant 

`1	149784224	149784224	C	T	FCGR1A`

should be called `VUS`, but the code essentially changes the PVS1, which is 1 into a 0 and as a result gives it the intervar call (Pathogenic) when it _should_ be a VUS (according to Jung). However, according to our logic documented in the readme, the conversion to PVS1=0 should be the case since the criterion is `na` in AutoPVS1 output. Pasted here: `if criterion is na|NF0  then PVS1 = 0; ` If we removed this rule, we would have gotten the VUS call. 

The question is, is this correct? Should we add something else to/modify/delete this? cc @jungkim2

**Comment by jungkim2** [comment]
Currently, InterVar says for that variant, PVS1=1, PP=2 (PP3, PP5). Based on autoPVS1 output, it is unmet (but this is another set of error that I need to figure out what is going on). 
With the above information, it will end of being PP=1 which will get to be VUS. 

https://autopvs1.bgi.com/variant/hg38/1-149784224-C-T (showing NF1)
autoPVS1 output shows gene to be H2BC18 intronic variant, not sure what is going on here.

**Comment by jungkim2** [comment]
Yes. That is correct. 
##VEP="v104" time="2023-06-26 10:25:36" cache="/fdb/VEP/104/cache/homo_sapiens_refseq/104_GRCh38" ensembl=104.1af1dce ensembl-funcgen=104.f1c7762 ensembl-io=104.1d3bb6e ensembl-variation=104.6154f8b

If I look at that specific position, VEP annotation says
`chr1	149784224	rs74315310	C	T	.	.	CSQ=T|stop_gained|HIGH|FCGR1A|2209|Transcript|NM_000566.4|protein_coding|3/6||NM_000566.4:c.274C>T|NP_000557.1:p.Arg92Ter|324|274|92|R/*|Cga/Tga|||1|||EntrezGene||||||chr1:g.149784224C>T,T|intron_variant|MODIFIER|H2BC18|440689|Transcript|NM_001161334.2|protein_coding||1/1|NM_001161334.2:c.378-964G>A|||||||||-1||1|EntrezGene||YES||||chr1:g.149784224C>T,T|stop_gained|HIGH|FCGR1A|2209|Transcript|NM_001378804.1|protein_coding|3/6||NM_001378804.1:c.277C>T|NP_001365733.1:p.Arg93Ter|327|277|93|R/*|Cga/Tga|||1|||EntrezGene||||||chr1:g.149784224C>T,T|stop_gained|HIGH|FCGR1A|2209|Transcript|NM_001378805.1|protein_coding|2/5||NM_001378805.1:c.253C>T|NP_001365734.1:p.Arg85Ter|303|253|85|R/*|Cga/Tga|||1|||EntrezGene||||||chr1:g.149784224C>T,T|stop_gained|HIGH|FCGR1A|2209|Transcript|NM_001378806.1|protein_coding|3/6||NM_001378806.1:c.274C>T|NP_001365735.1:p.Arg92Ter|324|274|92|R/*|Cga/Tga|||1|||EntrezGene||||||chr1:g.149784224C>T,T|stop_gained|HIGH|FCGR1A|2209|Transcript|NM_001378807.1|protein_coding|3/6||NM_001378807.1:c.205C>T|NP_001365736.1:p.Arg69Ter|295|205|69|R/*|Cga/Tga|||1|||EntrezGene||||||chr1:g.149784224C>T,T|stop_gained|HIGH|FCGR1A|2209|Transcript|NM_001378808.1|protein_coding|3/5||NM_001378808.1:c.274C>T|NP_001365737.1:p.Arg92Ter|324|274|92|R/*|Cga/Tga|||1|||EntrezGene||||||chr1:g.149784224C>T,T|intron_variant|MODIFIER|FCGR1A|2209|Transcript|NM_001378809.1|protein_coding||2/4|NM_001378809.1:c.52+1034C>T|||||||||1|||EntrezGene||||||chr1:g.149784224C>T,T|intron_variant|MODIFIER|FCGR1A|2209|Transcript|NM_001378810.1|protein_coding||1/3|NM_001378810.1:c.31+1450C>T|||||||||1|||EntrezGene||||||chr1:g.149784224C>T,T|intron_variant|MODIFIER|FCGR1A|2209|Transcript|NM_001378811.1|protein_coding||1/3|NM_001378811.1:c.31+1450C>T|||||||||1|||EntrezGene||||||chr1:g.149784224C>T,T|non_coding_transcript_exon_variant|MODIFIER|FCGR1A|2209|Transcript|NR_166121.1|misc_RNA|3/6||NR_166121.1:n.324C>T||324|||||||1|||EntrezGene||||||chr1:g.149784224C>T,T|non_coding_transcript_exon_variant|MODIFIER|FCGR1A|2209|Transcript|NR_166122.1|misc_RNA|3/7||NR_166122.1:n.324C>T||324|||||||1|||EntrezGene||||||chr1:g.14978422C>T,T|non_coding_transcript_exon_variant|MODIFIER|FCGR1A|2209|Transcript|NR_166123.1|misc_RNA|3/8||NR_166123.1:n.324C>T||324|||||||1|||EntrezGene||YES||||chr1:g.149784224C>T`

**Comment by jharenza** [comment]
Is the FCGR1A protein coding variant _also_ in autoPVS1 output? Is it possible that all transcript calls are there?

**Comment by jungkim2** [comment]
I think I know what is going on here. In above annotation, it seems like for some reason, VEP is saying that below annotation is the canonical and pick that particular transcript (which I am not sure why...) I can double check if that has to do with the way VEP annotation has been used... 

```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|PICK|SYMBOL_SOURCE|HGNC_ID|CANONICAL|REFSEQ_MATCH|REFSEQ_OFFSET|HGVS_OFFSET|HGVSg">
T|intron_variant|MODIFIER|H2BC18|440689|Transcript|NM_001161334.2|protein_coding||1/1|NM_001161334.2:c.378-964G>A|||||||||-1||1|EntrezGene||YES||||chr1:g.149784224C>T,T
```

**Comment by jungkim2** [comment]
Through investigation of VEP versioning, it has to do with VEP100-104 choosing H2BC18 as the canonical MANE select gene rather than FCGR1A. If VEP105-109 is used, it selects FCGR1A. 

Based on this current scheme, ClinVar 0 star getting ClinVar call has been fixed.
