### ISSUE TITLE
`out_annotations_report.abridged.tsv` located in multiple folders

### ISSUE THREAD

**Issue by jharenza** [diskin-lab-chop/AutoGVP#65]
`[out_annotations_report.abridged.tsv](https://github.com/diskin-lab-chop/AutoGVP/blob/main/AutoGVP/out_annotations_report.abridged.tsv)` exists in AutoGVP root and in results folder - check to be sure that this file is output to results folder from each set of scripts

**Comment by naqvia** [comment]
this must have just been carried over from older versions. Both scripts are putting output into the `results` folder in the root. 

```
results_dir <- file.path(root_dir, "results")

output_tab_abr_file <- paste0(output_name, ".custom_input.annotations_report.abridged.tsv")

# create results directory if it does not exist
if (!dir.exists(results_dir)) {
  dir.create(results_dir)
}

# write output to file in results folder
results_tab_abridged %>%
  write_tsv(
    file.path(results_dir, output_tab_abr_file),
    append = FALSE,
    quote = "none",
    col_names = TRUE
  )
```

will create PR to delete unnecc results folder

**Comment by jharenza** [comment]
completed with #92
