### ISSUE TITLE
Bug: missing variants from VCF on final output

### ISSUE THREAD

**Issue by jungkim2** [diskin-lab-chop/AutoGVP#77]
#### Provide the command used or report the bug here
started with 1,558,736 variants but final output only has 177,243 variants. 
Comparing with 7/13 version of R, the difference are coming from NA stars
Current output only has variants from ClinVar 0,1,2,3,4,1NR

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by naqvia** [comment]
This issue has been resolved. These were rare variants that did not have a clinVar entry and were getting unintentionally filtered out in the pipeline. They have been added back and now go through interVar and get an approp. final call.
