### ISSUE TITLE
Feature request: script to create comprehensive and abbreviated output files

### ISSUE THREAD

**Issue by rjcorb** [diskin-lab-chop/AutoGVP#81]
#### Briefly describe the feature and provide meaningful references

Merge all variant annotation data across files (VEP VCF, AutoGVP, multianno, intervar, autopvs1) and write comprehensive and abbreviated files to output. 

#### What input data are required for this feature or analysis?

- AutoGVP annotation output
- Parsed VEP VCF file
- multianno, intervar, autopvs1 files

#### How do you plan to organise the feature or analysis - will it be a multi-function call or add to existing functions?

A new R script `merge-variant-annotations.R` will be written to perform the following: 
- separate SNPEff annotations by gene/transcript, and parse info columns (gene id, impact, HGVSc, HGVSp, etc)
- Combine VCF with AutoGVP output and relevant information from other files (multianno, intervar, autopvs1)
- Save full results file to output, and subset to write out an abbreviated output with most relevant columns (variant, pathogenicity call, call source, gene symbol, etc). 

#### Who will complete the feature request (please add a GitHub handle here if relevant)?

@rjcorb

**Comment by rjcorb** [comment]
@naqvia @jharenza

**Comment by naqvia** [comment]
Issue resolved and PR merged
