### ISSUE TITLE
Bug: vcf parsing not capturing all INFO fields

### ISSUE THREAD

**Issue by rjcorb** [diskin-lab-chop/AutoGVP#89]
#### Provide the command used or report the bug here

The `parse_vcf.sh` is currently pulling INFO field names based on those present in first row of VCF, but this is causing some fields to be missed as they are only present with values in subsequent rows. The script needs to identify all INFO fields present in any row of vcf to be included in parsed output. 

#### What version are you using?

current version of scripts

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by naqvia** [comment]
this issue has been resolved!
